buildscript {
    repositories {
        google()
        mavenCentral()
        
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.0'
    }
}

plugins {
    id 'com.android.library'
    id 'maven-publish'
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
        mavenLocal()
    }
}

android {
    // Conditional for compatibility with AGP <4.2.
    if (project.android.hasProperty("namespace")) {
        namespace 'com.arthenica.ffmpegkit.flutter'
    }

    compileSdkVersion 33

    defaultConfig {
        minSdkVersion 24
        targetSdkVersion 33
        versionCode 603
        versionName "6.0.3"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    lintOptions {
        disable 'GradleCompatible'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.annotation:annotation:1.5.0'
    implementation 'com.arthenica:ffmpeg-kit:6.0.3'
    implementation "com.arthenica:smart-exception-java:0.2.1"
    implementation "com.arthenica:smart-exception-common:0.2.1"
}

publishing {
    publications {
        ffmpegAar(MavenPublication) {
            groupId = "com.arthenica"
            artifactId = "ffmpeg-kit"
            version  = "6.0.3"

            artifact(file("libs/ffmpeg-kit.aar")) {
                extension = "aar"
            }
        }

        smartExceptionJava(MavenPublication) {
            groupId = "com.arthenica"
            artifactId = "smart-exception-java"
            version  = "0.2.1"

            artifact(file("libs/smart-exception-java-0.2.1.jar")) {
                extension = "jar"
            }
        }

        smartExceptionCommon(MavenPublication) {
            groupId = "com.arthenica"
            artifactId = "smart-exception-common"
            version  = "0.2.1"

            artifact(file("libs/smart-exception-common-0.2.1.jar")) {
                extension = "jar"
            }
        }
    }
}

preBuild.dependsOn(':ffmpeg_kit_flutter:publishToMavenLocal')
